### ISSUE TITLE
Unable to download the plugin

### ISSUE THREAD

**Issue by bonddim** [BetterCorp/cloudflarewarp#12]
Hi!
traefik fails on plugin download:
```
time="2022-08-01T20:12:04Z" level=debug msg="loading of plugin: cloudflarewarp: github.com/BetterCorp/cloudflarewarp@v2.1.0"
2022/08/01 20:12:05 traefik.go:80: command traefik error: failed to download plugin github.com/BetterCorp/cloudflarewarp: error: 500: {"error":"Failed to get plugin github.com/BetterCorp/cloudflarewarp@v2.1.0"}
```
Checked versions:
traefik: v2.8.0, v2.8.1
plugin: v2.0.0, v2.1.0

**Comment by bonddim** [comment]
Probably, this is related to #11

**Comment by mrinc** [comment]
Added tests to isolate the issue - https://github.com/BetterCorp/cloudflarewarp/actions/runs/2782040700 
We can now make sure tags/versions correctly pull with traefik.

Will find out what is going on and go from there once this job runs (and fails).

**Comment by mrinc** [comment]
It's definitely something specific to traefik in the way it pulls down the plugin.
A standard git clone within the docker image succeeds.

Will log a ticket with traefik for this

**Comment by mrinc** [comment]
Ok should be fixed now - https://github.com/BetterCorp/cloudflarewarp/releases/tag/v1.3.0  

Once traefik runs it's plugin sync, it should be all good - note version change - `1.3.0` instead of `2.1.0`

**Comment by charl3y15** [comment]
Still giving me the same issue 

`command traefik error: failed to download plugin github.com/BetterCorp/cloudflarewarp: error: 404: {"error":"Unknown plugin: github.com/BetterCorp/cloudflarewarp@v1.3.0"}`

**Comment by mrinc** [comment]
Traefik had an issue with the repo : https://github.com/traefik/traefik/issues/9225#issuecomment-1203083085 

Just pushing up some cleanups now too see.

**Comment by mrinc** [comment]
Okay it's now showing up in the catalog woop :) 

Now to run the test :D

**Comment by mrinc** [comment]
[![Integration Test](https://github.com/BetterCorp/cloudflarewarp/actions/workflows/prodTest.yml/badge.svg)](https://github.com/BetterCorp/cloudflarewarp/actions/workflows/prodTest.yml)  

Looks good now, give that puppy a test and let me know if all good now?

**Comment by mrinc** [comment]
I've just upped the version to v1.3.1 - but there are no code changes, so you can use either 1.3.0 or 1.3.1  
It's just to force the update on Traefiks catalog with the name change to reflect more-of what the plugin really does.
