### ISSUE TITLE
not working as default ip whitelist

### ISSUE THREAD

**Issue by milindpatel63** [BetterCorp/cloudflarewarp#18]
In default config, it should inly allow connection from cloudflare ip's, and block all other requests from other ip's, including requests in LAN network.
But I can successfully connect to my traefik host via lan IP.
My local subnet is 172.26.30.0/23

I have tried setting disabledefault to true and then adding all cloudflare ips in trust ip's and NOT adding my plan network subnet. Still I am able to connect via lan.
I am doubtful, does this even work?

**Comment by mrinc** [comment]
`"This plugin solves this issue by overwriting the X-Real-IP and X-Forwarded-For with an IP from the CF-Connecting-IP header."`  

It does not block requests, only rewrite the header.  

We do add a `X-Is-Trusted` header which is either `yes` `no` `danger` (danger is when something is not right with the request and we failed to even parse it.  
So you could use that header to block all requests on your webserver that are not trusted (`yes`).
