### ISSUE TITLE
With v2.11.2 of traefik doesn't work

### ISSUE THREAD

**Issue by txolo99** [BetterCorp/cloudflarewarp#31]
With v2.11.2 of traefik version doesn't work

Please could you verify this?

**Comment by mrinc** [comment]
https://github.com/BetterCorp/cloudflarewarp/actions/runs/8587415216/job/23531025468#step:13:41  
https://github.com/BetterCorp/cloudflarewarp/actions/runs/8806669105/job/24171994305#step:13:37  

Seems to work fine with the latest traefik hey  

Maybe post your config and what you are issues you have and we can go from there

**Comment by txolo99** [comment]
The Traefik image hadn't downloaded properly, which was causing issues. It wasn't a problem with the plugin
